### ISSUE TITLE
"IndexError: list index out of range" Error applying "Split Trajectories at Time Intervals" to filtered layer

### ISSUE THREAD

**Issue by benparkergit** [movingpandas/qgis-processing-trajectory#23]
I hope I am doing this right... The tool is super-useful for my work, thank you. 

I filtered a point layer of AIS ship data, to reduce it to three MMSI numbers. 

Then I ran the "Split Trajectories at Time Intervals" on the filtered layer and I get this error:

```
QGIS version: 3.34.3-Prizren
Qt version: 5.15.8
Python version: 3.10.13
GDAL version: 3.8.3
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.2 (git-version: Release)
Algorithm started at: 2024-02-27T13:28:43
Algorithm 'Split trajectories at time intervals' starting…
Input parameters:
{ 'INPUT' : QgsProcessingFeatureSourceDefinition('file:///C:/Users/BPARKER2/OneDrive%20-%20United%20Nations/Documents/JCC/BSISO-2024/Data/UNGM/NOVO1.csv?type=csv&trimFields=Yes&maxFields=10000&detectTypes=no&xField=longitude&yField=latitude&crs=EPSG:4326&spatialIndex=no&subsetIndex=no&watchFile=no&field=dt_pos_utc:datetime&field=heading:double&subset=%22mmsi%22%20%20%20LIKE%20%20229084000%20OR%20%22mmsi%22%20%20%20LIKE%20%20636020581%20OR%20%22mmsi%22%20LIKE%20314733000', selectedFeaturesOnly=False, featureLimit=-1, flags=QgsProcessingFeatureSourceDefinition.FlagCreateIndividualOutputPerInputFeature, geometryCheck=QgsFeatureRequest.GeometryAbortOnInvalid), 'OUTPUT_PTS' : 'TEMPORARY_OUTPUT', 'OUTPUT_TRAJS' : 'TEMPORARY_OUTPUT', 'SPEED_UNIT' : 'km/h', 'SPLIT_MODE' : 2, 'TIME_FIELD' : 'dt_pos_utc', 'TRAJ_ID_FIELD' : 'mmsi' }

Executing iteration 1/593…
Traceback (most recent call last):
File "C:\Users/BPARKER2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_trajectory\qgis_processing\trajectoriesAlgorithm.py", line 161, in processAlgorithm
QgsField(tc.get_speed_col(), QVariant.Double),
File "C:\Users\BPARKER2\AppData\Local\miniforge3\lib\site-packages\movingpandas\trajectory_collection.py", line 281, in get_speed_col
return self.trajectories[0].get_speed_col()
IndexError: list index out of range



```

**Comment by anitagraser** [comment]
Thank you for the report.  Can you share the data sample to reproduce the error?

**Comment by anitagraser** [comment]
I've tested applying a filter to the AIS sample shipped with the plugin but I cannot reproduce the issue this way.

**Comment by anitagraser** [comment]
@benparkergit Can you  test with the new development version to see if you get the new and improved error message? 
![image](https://github.com/movingpandas/qgis-processing-trajectory/assets/590385/0eb7f1ba-9e09-45d3-929d-97d45b86a712)

**Comment by benparkergit** [comment]
I am very sorry I cannot reproduce the error. I will keep trying and report back.

**Comment by anitagraser** [comment]
No worries. Let's reopen this issue when you find something.
