### ISSUE TITLE
error running extract segments (gtfs)

### ISSUE THREAD

**Issue by idshklein** [movingpandas/qgis-processing-trajectory#38]
hi, 
I try to run Extract segments on the gtfs file linked in this blog post:
https://anitagraser.com/2024/05/04/gtfs-algorithms-about-to-land-in-trajectools/
i.e. this link
https://www.mobilitydata.gv.at/daten/soll-fahrplandaten-gtfshttps://www.mobilitydata.gv.at/daten/soll-fahrplandaten-gtfs
I assume it is the one here:
![image](https://github.com/user-attachments/assets/60bfd795-0240-47c9-9e63-e99b6154b8e6)

extract shapes works just fine. 

running extract segments, gives the following error:
Traceback (most recent call last):
File "C:\Users/idshk/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_trajectory\qgis_processing\gtfsAlgorithm.py", line 194, in processAlgorithm
segments = self.get_segments(feed, add_avg_speed)
File "C:\Users/idshk/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_trajectory\qgis_processing\gtfsAlgorithm.py", line 230, in get_segments
segments = feed.segments
File "C:\OSGeo4W\apps\Python39\lib\site-packages\gtfs_functions\gtfs_functions.py", line 234, in segments
self._segments = self.get_segments()
File "C:\OSGeo4W\apps\Python39\lib\site-packages\gtfs_functions\gtfs_functions.py", line 835, in get_segments
stop_times = self.stop_times
File "C:\OSGeo4W\apps\Python39\lib\site-packages\gtfs_functions\gtfs_functions.py", line 206, in stop_times
self._stop_times = self.get_stop_times()
File "C:\OSGeo4W\apps\Python39\lib\site-packages\gtfs_functions\gtfs_functions.py", line 679, in get_stop_times
trips = self.trips
File "C:\OSGeo4W\apps\Python39\lib\site-packages\gtfs_functions\gtfs_functions.py", line 176, in trips
self._trips = self.get_trips()
File "C:\OSGeo4W\apps\Python39\lib\site-packages\gtfs_functions\gtfs_functions.py", line 621, in get_trips
trips = trips.set_index('service_id').join(
File "C:\Users\idshk\AppData\Roaming\Python\Python39\site-packages\pandas\util\_decorators.py", line 311, in wrapper
return func(*args, **kwargs)
TypeError: reset_index() got an unexpected keyword argument 'names'

**Comment by anitagraser** [comment]
Yes, that's the correct file. However, I cannot reproduce the error you mention. As you can see from the following screenshot, I don't get an error with this dataset: 

![image](https://github.com/user-attachments/assets/170ebeec-8e08-49c0-b608-c4451856942a)

Maybe there has been an issue with the download?
