### ISSUE TITLE
AttributeError in Intersect trajectories with polygon layer

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/qgis-processing-trajectory#41]
```
QGIS version: 3.34.2-Prizren
Qt version: 5.15.8
Python version: 3.9.18
GDAL version: 3.8.3
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.2 (git-version: Release)
Algorithm started at: 2024-09-25T12:07:41
Algorithm 'Intersect trajectories with polygon layer' starting…
Input parameters:
{ 'INPUT' : 'C:/Users/GraserA/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/processing_trajectory/sample_data/geolife.gpkg|layername=testdata_geolife2', 'MIN_LENGTH' : 0, 'OUTPUT_PTS' : 'TEMPORARY_OUTPUT', 'OUTPUT_TRAJS' : 'TEMPORARY_OUTPUT', 'OVERLAY_LAYER' : 'C:/Users/GraserA/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/processing_trajectory/sample_data/polys.geojson', 'SPEED_UNIT' : 'km/h', 'TIME_FIELD' : 't', 'TRAJ_ID_FIELD' : 'trajectory_id' }

Traceback (most recent call last):
File "C:\Users/GraserA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_trajectory\qgis_processing\trajectoriesAlgorithm.py", line 193, in processAlgorithm
self.processTc(tc, parameters, context)
File "C:\Users/GraserA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_trajectory\qgis_processing\overlayAlgorithm.py", line 207, in processTc
intersecting = tc.intersection(shapely_feature)
AttributeError: 'TrajectoryCollection' object has no attribute 'intersection'

Execution failed after 1.67 seconds

Loading resulting layers
Algorithm 'Intersect trajectories with polygon layer' finished
```

**Comment by anitagraser** [comment]
This algorithm requires movingpandas>=0.18.0 https://github.com/movingpandas/movingpandas/releases/tag/v0.18
